# Generated by Django 4.1.9 on 2023-05-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'managed': False},
        ),
    ]
