# Generated by Django 4.1.9 on 2023-05-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0002_alter_point_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={},
        ),
    ]
