# Generated by Django 4.1.9 on 2023-05-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0004_qgispoints'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qgispoints',
            table='points_all',
        ),
    ]
