# Generated by Django 4.1.9 on 2023-06-05 09:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0005_alter_qgispoints_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'points_all',
                'managed': False,
            },
        ),
    ]
